name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      #初始化git
      #- name: Set up SSH
      #  run: |
      #    mkdir -p ~/.ssh/
      #    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
       #   chmod 600 ~/.ssh/id_rsa
       #   ssh-keyscan 116.62.234.88 >> ~/.ssh/known_hosts
        #  eval `ssh-agent -s`
        #  ssh-add ~/.ssh/id_rsa

      #   - name: Deploy to server
      #     run: |
      #       ssh root@116.62.234.88 'cd /root/data/lingfeng && bash deploy.sh'
      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT_PORT }}
          remote_user: ${{ secrets.USERNAME }}
          SOURCE: .
          TARGET: /www/wwwroot/testAction
          args: --exclude=/www/wwwroot/testAction/public/upload --exclude=/www/wwwroot/testAction/runtime
