name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .idea/
      - LICENSE
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

    #  - name: Install dependencies
    #    run: composer install

    #  - name: Run tests
    #    run: composer test

    #  - name: Build application
     #   run : composer build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2
        with:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #        ARGS: -avz --delete --exclude='*.env' --exclude='runtime/'
          REMOTE_USER: ${{ secrets.USERNAME }}
     #     password: ${{ secrets.PASSWORD }}
          source: './'
          target: 'data/lingfeng/testAction'
